In [37]:
import pandas as pd
import re
from collections import defaultdict

In [2]:
df = pd.read_csv("time_series_60min_singleindex_filtered.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50401 entries, 0 to 50400
Columns: 300 entries, utc_timestamp to UA_load_forecast_entsoe_transparency
dtypes: float64(298), object(2)
memory usage: 115.4+ MB

In [3]:
df.head()

,utc_timestamp,cet_cest_timestamp,AT_load_actual_entsoe_transparency,AT_load_forecast_entsoe_transparency,AT_price_day_ahead,AT_solar_generation_actual,AT_wind_onshore_generation_actual,BE_load_actual_entsoe_transparency,BE_load_forecast_entsoe_transparency,BE_solar_generation_actual,...,SI_load_actual_entsoe_transparency,SI_load_forecast_entsoe_transparency,SI_solar_generation_actual,SI_wind_onshore_generation_actual,SK_load_actual_entsoe_transparency,SK_load_forecast_entsoe_transparency,SK_solar_generation_actual,SK_wind_onshore_generation_actual,UA_load_actual_entsoe_transparency,UA_load_forecast_entsoe_transparency
0,2014-12-31T23:00:00Z,2015-01-01T00:00:00+0100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2015-01-01T00:00:00Z,2015-01-01T01:00:00+0100,5946.0,6701.0,35.0,NaN,69.0,9484.0,9897.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2015-01-01T01:00:00Z,2015-01-01T02:00:00+0100,5726.0,6593.0,45.0,NaN,64.0,9152.0,9521.0,NaN,...,1045.47,816.0,NaN,1.17,2728.0,2860.0,3.8,NaN,NaN,NaN
3,2015-01-01T02:00:00Z,2015-01-01T03:00:00+0100,5347.0,6482.0,41.0,NaN,65.0,8799.0,9135.0,NaN,...,1004.79,805.0,NaN,1.04,2626.0,2810.0,3.8,NaN,NaN,NaN
4,2015-01-01T03:00:00Z,2015-01-01T04:00:00+0100,5249.0,6454.0,38.0,NaN,64.0,8567.0,8909.0,NaN,...,983.79,803.0,NaN,1.61,2618.0,2780.0,3.8,NaN,NaN,NaN

In [7]:
dummy = df.columns.tolist()
selected_columns = []

selected_columns.append(dummy[:2])
selected_columns

[['utc_timestamp', 'cet_cest_timestamp']]

In [10]:
dummy[2:7]

['AT_load_actual_entsoe_transparency',
 'AT_load_forecast_entsoe_transparency',
 'AT_price_day_ahead',
 'AT_solar_generation_actual',
 'AT_wind_onshore_generation_actual']

In [13]:
dummy[8:13]

['BE_load_forecast_entsoe_transparency',
 'BE_solar_generation_actual',
 'BE_wind_generation_actual',
 'BE_wind_offshore_generation_actual',
 'BE_wind_onshore_generation_actual']

In [14]:
dummy[14:19]

['BG_load_forecast_entsoe_transparency',
 'BG_solar_generation_actual',
 'BG_wind_onshore_generation_actual',
 'CH_load_actual_entsoe_transparency',
 'CH_load_forecast_entsoe_transparency']

In [15]:
areas = dummy[2:]
areas

['AT_load_actual_entsoe_transparency',
 'AT_load_forecast_entsoe_transparency',
 'AT_price_day_ahead',
 'AT_solar_generation_actual',
 'AT_wind_onshore_generation_actual',
 'BE_load_actual_entsoe_transparency',
 'BE_load_forecast_entsoe_transparency',
 'BE_solar_generation_actual',
 'BE_wind_generation_actual',
 'BE_wind_offshore_generation_actual',
 'BE_wind_onshore_generation_actual',
 'BG_load_actual_entsoe_transparency',
 'BG_load_forecast_entsoe_transparency',
 'BG_solar_generation_actual',
 'BG_wind_onshore_generation_actual',
 'CH_load_actual_entsoe_transparency',
 'CH_load_forecast_entsoe_transparency',
 'CH_solar_capacity',
 'CH_solar_generation_actual',
 'CH_wind_onshore_capacity',
 'CH_wind_onshore_generation_actual',
 'CY_load_actual_entsoe_transparency',
 'CY_load_forecast_entsoe_transparency',
 'CY_wind_onshore_generation_actual',
 'CZ_load_actual_entsoe_transparency',
 'CZ_load_forecast_entsoe_transparency',
 'CZ_solar_generation_actual',
 'CZ_wind_onshore_generation_actual',
 'DE_load_actual_entsoe_transparency',
 'DE_load_forecast_entsoe_transparency',
 'DE_solar_capacity',
 'DE_solar_generation_actual',
 'DE_solar_profile',
 'DE_wind_capacity',
 'DE_wind_generation_actual',
 'DE_wind_profile',
 'DE_wind_offshore_capacity',
 'DE_wind_offshore_generation_actual',
 'DE_wind_offshore_profile',
 'DE_wind_onshore_capacity',
 'DE_wind_onshore_generation_actual',
 'DE_wind_onshore_profile',
 'DE_50hertz_load_actual_entsoe_transparency',
 'DE_50hertz_load_forecast_entsoe_transparency',
 'DE_50hertz_solar_generation_actual',
 'DE_50hertz_wind_generation_actual',
 'DE_50hertz_wind_offshore_generation_actual',
 'DE_50hertz_wind_onshore_generation_actual',
 'DE_LU_load_actual_entsoe_transparency',
 'DE_LU_load_forecast_entsoe_transparency',
 'DE_LU_price_day_ahead',
 'DE_LU_solar_generation_actual',
 'DE_LU_wind_generation_actual',
 'DE_LU_wind_offshore_generation_actual',
 'DE_LU_wind_onshore_generation_actual',
 'DE_amprion_load_actual_entsoe_transparency',
 'DE_amprion_load_forecast_entsoe_transparency',
 'DE_amprion_solar_generation_actual',
 'DE_amprion_wind_onshore_generation_actual',
 'DE_tennet_load_actual_entsoe_transparency',
 'DE_tennet_load_forecast_entsoe_transparency',
 'DE_tennet_solar_generation_actual',
 'DE_tennet_wind_generation_actual',
 'DE_tennet_wind_offshore_generation_actual',
 'DE_tennet_wind_onshore_generation_actual',
 'DE_transnetbw_load_actual_entsoe_transparency',
 'DE_transnetbw_load_forecast_entsoe_transparency',
 'DE_transnetbw_solar_generation_actual',
 'DE_transnetbw_wind_onshore_generation_actual',
 'DK_load_actual_entsoe_transparency',
 'DK_load_forecast_entsoe_transparency',
 'DK_solar_capacity',
 'DK_solar_generation_actual',
 'DK_wind_capacity',
 'DK_wind_generation_actual',
 'DK_wind_offshore_capacity',
 'DK_wind_offshore_generation_actual',
 'DK_wind_onshore_capacity',
 'DK_wind_onshore_generation_actual',
 'DK_1_load_actual_entsoe_transparency',
 'DK_1_load_forecast_entsoe_transparency',
 'DK_1_price_day_ahead',
 'DK_1_solar_generation_actual',
 'DK_1_wind_generation_actual',
 'DK_1_wind_offshore_generation_actual',
 'DK_1_wind_onshore_generation_actual',
 'DK_2_load_actual_entsoe_transparency',
 'DK_2_load_forecast_entsoe_transparency',
 'DK_2_price_day_ahead',
 'DK_2_solar_generation_actual',
 'DK_2_wind_generation_actual',
 'DK_2_wind_offshore_generation_actual',
 'DK_2_wind_onshore_generation_actual',
 'EE_load_actual_entsoe_transparency',
 'EE_load_forecast_entsoe_transparency',
 'EE_solar_generation_actual',
 'EE_wind_onshore_generation_actual',
 'ES_load_actual_entsoe_transparency',
 'ES_load_forecast_entsoe_transparency',
 'ES_solar_generation_actual',
 'ES_wind_onshore_generation_actual',
 'FI_load_actual_entsoe_transparency',
 'FI_load_forecast_entsoe_transparency',
 'FI_wind_onshore_generation_actual',
 'FR_load_actual_entsoe_transparency',
 'FR_load_forecast_entsoe_transparency',
 'FR_solar_generation_actual',
 'FR_wind_onshore_generation_actual',
 'GB_GBN_load_actual_entsoe_transparency',
 'GB_GBN_load_forecast_entsoe_transparency',
 'GB_GBN_price_day_ahead',
 'GB_GBN_solar_capacity',
 'GB_GBN_solar_generation_actual',
 'GB_GBN_solar_profile',
 'GB_GBN_wind_capacity',
 'GB_GBN_wind_generation_actual',
 'GB_GBN_wind_profile',
 'GB_GBN_wind_offshore_capacity',
 'GB_GBN_wind_offshore_generation_actual',
 'GB_GBN_wind_offshore_profile',
 'GB_GBN_wind_onshore_capacity',
 'GB_GBN_wind_onshore_generation_actual',
 'GB_GBN_wind_onshore_profile',
 'GB_NIR_load_actual_entsoe_transparency',
 'GB_NIR_load_forecast_entsoe_transparency',
 'GB_NIR_solar_capacity',
 'GB_NIR_wind_onshore_capacity',
 'GB_NIR_wind_onshore_generation_actual',
 'GB_UKM_load_actual_entsoe_transparency',
 'GB_UKM_load_forecast_entsoe_transparency',
 'GB_UKM_solar_capacity',
 'GB_UKM_solar_generation_actual',
 'GB_UKM_wind_capacity',
 'GB_UKM_wind_generation_actual',
 'GB_UKM_wind_offshore_capacity',
 'GB_UKM_wind_offshore_generation_actual',
 'GB_UKM_wind_onshore_capacity',
 'GB_UKM_wind_onshore_generation_actual',
 'GR_load_actual_entsoe_transparency',
 'GR_load_forecast_entsoe_transparency',
 'GR_solar_generation_actual',
 'GR_wind_onshore_generation_actual',
 'HR_load_actual_entsoe_transparency',
 'HR_load_forecast_entsoe_transparency',
 'HR_solar_generation_actual',
 'HR_wind_onshore_generation_actual',
 'HU_load_actual_entsoe_transparency',
 'HU_load_forecast_entsoe_transparency',
 'HU_solar_generation_actual',
 'HU_wind_onshore_generation_actual',
 'IE_load_actual_entsoe_transparency',
 'IE_load_forecast_entsoe_transparency',
 'IE_wind_onshore_generation_actual',
 'IE_sem_load_actual_entsoe_transparency',
 'IE_sem_load_forecast_entsoe_transparency',
 'IE_sem_price_day_ahead',
 'IE_sem_wind_onshore_generation_actual',
 'IT_load_actual_entsoe_transparency',
 'IT_load_forecast_entsoe_transparency',
 'IT_solar_generation_actual',
 'IT_wind_onshore_generation_actual',
 'IT_BRNN_price_day_ahead',
 'IT_BRNN_wind_onshore_generation_actual',
 'IT_CNOR_load_actual_entsoe_transparency',
 'IT_CNOR_load_forecast_entsoe_transparency',
 'IT_CNOR_price_day_ahead',
 'IT_CNOR_solar_generation_actual',
 'IT_CNOR_wind_onshore_generation_actual',
 'IT_CSUD_load_actual_entsoe_transparency',
 'IT_CSUD_load_forecast_entsoe_transparency',
 'IT_CSUD_price_day_ahead',
 'IT_CSUD_solar_generation_actual',
 'IT_CSUD_wind_onshore_generation_actual',
 'IT_FOGN_price_day_ahead',
 'IT_FOGN_solar_generation_actual',
 'IT_FOGN_wind_onshore_generation_actual',
 'IT_GR_price_day_ahead',
 'IT_NORD_load_actual_entsoe_transparency',
 'IT_NORD_load_forecast_entsoe_transparency',
 'IT_NORD_price_day_ahead',
 'IT_NORD_solar_generation_actual',
 'IT_NORD_wind_onshore_generation_actual',
 'IT_NORD_AT_price_day_ahead',
 'IT_NORD_CH_price_day_ahead',
 'IT_NORD_FR_price_day_ahead',
 'IT_NORD_SI_price_day_ahead',
 'IT_PRGP_price_day_ahead',
 'IT_PRGP_solar_generation_actual',
 'IT_PRGP_wind_onshore_generation_actual',
 'IT_ROSN_price_day_ahead',
 'IT_ROSN_solar_generation_actual',
 'IT_ROSN_wind_onshore_generation_actual',
 'IT_SACO_AC_price_day_ahead',
 'IT_SACO_DC_price_day_ahead',
 'IT_SARD_load_actual_entsoe_transparency',
 'IT_SARD_load_forecast_entsoe_transparency',
 'IT_SARD_price_day_ahead',
 'IT_SARD_solar_generation_actual',
 'IT_SARD_wind_onshore_generation_actual',
 'IT_SICI_load_actual_entsoe_transparency',
 'IT_SICI_load_forecast_entsoe_transparency',
 'IT_SICI_price_day_ahead',
 'IT_SICI_solar_generation_actual',
 'IT_SICI_wind_onshore_generation_actual',
 'IT_SUD_load_actual_entsoe_transparency',
 'IT_SUD_load_forecast_entsoe_transparency',
 'IT_SUD_price_day_ahead',
 'IT_SUD_solar_generation_actual',
 'IT_SUD_wind_onshore_generation_actual',
 'LT_load_actual_entsoe_transparency',
 'LT_load_forecast_entsoe_transparency',
 'LT_solar_generation_actual',
 'LT_wind_onshore_generation_actual',
 'LU_load_actual_entsoe_transparency',
 'LU_load_forecast_entsoe_transparency',
 'LV_load_actual_entsoe_transparency',
 'LV_load_forecast_entsoe_transparency',
 'LV_wind_onshore_generation_actual',
 'ME_load_actual_entsoe_transparency',
 'ME_load_forecast_entsoe_transparency',
 'ME_wind_onshore_generation_actual',
 'NL_load_actual_entsoe_transparency',
 'NL_load_forecast_entsoe_transparency',
 'NL_solar_generation_actual',
 'NL_wind_generation_actual',
 'NL_wind_offshore_generation_actual',
 'NL_wind_onshore_generation_actual',
 'NO_load_actual_entsoe_transparency',
 'NO_load_forecast_entsoe_transparency',
 'NO_wind_onshore_generation_actual',
 'NO_1_load_actual_entsoe_transparency',
 'NO_1_load_forecast_entsoe_transparency',
 'NO_1_price_day_ahead',
 'NO_1_wind_onshore_generation_actual',
 'NO_2_load_actual_entsoe_transparency',
 'NO_2_load_forecast_entsoe_transparency',
 'NO_2_price_day_ahead',
 'NO_2_wind_onshore_generation_actual',
 'NO_3_load_actual_entsoe_transparency',
 'NO_3_load_forecast_entsoe_transparency',
 'NO_3_price_day_ahead',
 'NO_3_wind_onshore_generation_actual',
 'NO_4_load_actual_entsoe_transparency',
 'NO_4_load_forecast_entsoe_transparency',
 'NO_4_price_day_ahead',
 'NO_4_wind_onshore_generation_actual',
 'NO_5_load_actual_entsoe_transparency',
 'NO_5_load_forecast_entsoe_transparency',
 'NO_5_price_day_ahead',
 'NO_5_wind_onshore_generation_actual',
 'PL_load_actual_entsoe_transparency',
 'PL_load_forecast_entsoe_transparency',
 'PL_solar_generation_actual',
 'PL_wind_onshore_generation_actual',
 'PT_load_actual_entsoe_transparency',
 'PT_load_forecast_entsoe_transparency',
 'PT_solar_generation_actual',
 'PT_wind_generation_actual',
 'PT_wind_offshore_generation_actual',
 'PT_wind_onshore_generation_actual',
 'RO_load_actual_entsoe_transparency',
 'RO_load_forecast_entsoe_transparency',
 'RO_solar_generation_actual',
 'RO_wind_onshore_generation_actual',
 'RS_load_actual_entsoe_transparency',
 'RS_load_forecast_entsoe_transparency',
 'SE_load_actual_entsoe_transparency',
 'SE_load_forecast_entsoe_transparency',
 'SE_wind_capacity',
 'SE_wind_offshore_capacity',
 'SE_wind_onshore_capacity',
 'SE_wind_onshore_generation_actual',
 'SE_1_load_actual_entsoe_transparency',
 'SE_1_load_forecast_entsoe_transparency',
 'SE_1_price_day_ahead',
 'SE_1_wind_onshore_generation_actual',
 'SE_2_load_actual_entsoe_transparency',
 'SE_2_load_forecast_entsoe_transparency',
 'SE_2_price_day_ahead',
 'SE_2_wind_onshore_generation_actual',
 'SE_3_load_actual_entsoe_transparency',
 'SE_3_load_forecast_entsoe_transparency',
 'SE_3_price_day_ahead',
 'SE_3_wind_onshore_generation_actual',
 'SE_4_load_actual_entsoe_transparency',
 'SE_4_load_forecast_entsoe_transparency',
 'SE_4_price_day_ahead',
 'SE_4_wind_onshore_generation_actual',
 'SI_load_actual_entsoe_transparency',
 'SI_load_forecast_entsoe_transparency',
 'SI_solar_generation_actual',
 'SI_wind_onshore_generation_actual',
 'SK_load_actual_entsoe_transparency',
 'SK_load_forecast_entsoe_transparency',
 'SK_solar_generation_actual',
 'SK_wind_onshore_generation_actual',
 'UA_load_actual_entsoe_transparency',
 'UA_load_forecast_entsoe_transparency']

In [16]:
c = areas[0]
c[:2]

'AT'

In [30]:
code_area = []

for col in areas:
    if col[:2] == "DE":
        # will handle this later bcs there are so many types of DE
        continue
    if col[:2] not in code_area:
        code_area.append(col[:2])
    else:
        continue

print(f"Total number of code area: {len(code_area)}")
print(f"List of code area: {code_area}")

Total number of code area: 31
List of code area: ['AT', 'BE', 'BG', 'CH', 'CY', 'CZ', 'DK', 'EE', 'ES', 'FI', 'FR', 'GB', 'GR', 'HR', 'HU', 'IE', 'IT', 'LT', 'LU', 'LV', 'ME', 'NL', 'NO', 'PL', 'PT', 'RO', 'RS', 'SE', 'SI', 'SK', 'UA']

In [27]:
DE_area = []

for col in areas:
    if col[:2] == "DE":
        DE_area.append(col)

In [26]:
pattern

'load|solar|wind|price|capacity|generation'

In [31]:
keywords = ['load', 'solar', 'wind', 'price', 'capacity', 'generation']
pattern = '|'.join(keywords)

for col in DE_area:
    # Cari posisi keyword pertama kali muncul
    match = re.search(f"_({pattern})", col)
    if match:
        # Ambil string sebelum underscore keyword tersebut
        area_code = col[:match.start()]
        if area_code not in code_area:
            code_area.append(area_code)
        else:
            continue
    else:
        continue

print(f"Total number of code area: {len(code_area)}")
print(f"List of code area: {code_area}")

Total number of code area: 37
List of code area: ['AT', 'BE', 'BG', 'CH', 'CY', 'CZ', 'DK', 'EE', 'ES', 'FI', 'FR', 'GB', 'GR', 'HR', 'HU', 'IE', 'IT', 'LT', 'LU', 'LV', 'ME', 'NL', 'NO', 'PL', 'PT', 'RO', 'RS', 'SE', 'SI', 'SK', 'UA', 'DE', 'DE_50hertz', 'DE_LU', 'DE_amprion', 'DE_tennet', 'DE_transnetbw']

In [35]:
x = [i for i in areas if i[:2] == 'AT']

In [36]:
x

['AT_load_actual_entsoe_transparency',
 'AT_load_forecast_entsoe_transparency',
 'AT_price_day_ahead',
 'AT_solar_generation_actual',
 'AT_wind_onshore_generation_actual']

In [43]:
df_AT__ = df[['utc_timestamp', 'cet_cest_timestamp']]
df_AT__ = pd.concat([df_AT__, df[[i for i in areas if i[:2] == 'AT']]], axis=1)
df_AT__.head()

,utc_timestamp,cet_cest_timestamp,AT_load_actual_entsoe_transparency,AT_load_forecast_entsoe_transparency,AT_price_day_ahead,AT_solar_generation_actual,AT_wind_onshore_generation_actual
0,2014-12-31T23:00:00Z,2015-01-01T00:00:00+0100,NaN,NaN,NaN,NaN,NaN
1,2015-01-01T00:00:00Z,2015-01-01T01:00:00+0100,5946.0,6701.0,35.0,NaN,69.0
2,2015-01-01T01:00:00Z,2015-01-01T02:00:00+0100,5726.0,6593.0,45.0,NaN,64.0
3,2015-01-01T02:00:00Z,2015-01-01T03:00:00+0100,5347.0,6482.0,41.0,NaN,65.0
4,2015-01-01T03:00:00Z,2015-01-01T04:00:00+0100,5249.0,6454.0,38.0,NaN,64.0

In [45]:
df_each_area = defaultdict(pd.DataFrame)

In [46]:
df_each_area

defaultdict(pandas.core.frame.DataFrame, {})

In [52]:
df_each_area = {}

for code in code_area:
    dummy_df = df[['utc_timestamp', 'cet_cest_timestamp']]
    dummy_val = df[[i for i in areas if i[:2] == code]]
    dummy_df = pd.concat([dummy_df, dummy_val], axis=1)

    key_code = 'df_' + code
    dummy_dict = {
        key_code: dummy_df
    }

    df_each_area |= dummy_dict

In [56]:
df_each_area.keys()

dict_keys(['df_AT', 'df_BE', 'df_BG', 'df_CH', 'df_CY', 'df_CZ', 'df_DK', 'df_EE', 'df_ES', 'df_FI', 'df_FR', 'df_GB', 'df_GR', 'df_HR', 'df_HU', 'df_IE', 'df_IT', 'df_LT', 'df_LU', 'df_LV', 'df_ME', 'df_NL', 'df_NO', 'df_PL', 'df_PT', 'df_RO', 'df_RS', 'df_SE', 'df_SI', 'df_SK', 'df_UA', 'df_DE', 'df_DE_50hertz', 'df_DE_LU', 'df_DE_amprion', 'df_DE_tennet', 'df_DE_transnetbw'])

In [62]:
for i, j in df_each_area.items():
    print(j)

              utc_timestamp        cet_cest_timestamp  \
0      2014-12-31T23:00:00Z  2015-01-01T00:00:00+0100
1      2015-01-01T00:00:00Z  2015-01-01T01:00:00+0100
2      2015-01-01T01:00:00Z  2015-01-01T02:00:00+0100
3      2015-01-01T02:00:00Z  2015-01-01T03:00:00+0100
4      2015-01-01T03:00:00Z  2015-01-01T04:00:00+0100
...                     ...                       ...
50396  2020-09-30T19:00:00Z  2020-09-30T21:00:00+0200
50397  2020-09-30T20:00:00Z  2020-09-30T22:00:00+0200
50398  2020-09-30T21:00:00Z  2020-09-30T23:00:00+0200
50399  2020-09-30T22:00:00Z  2020-10-01T00:00:00+0200
50400  2020-09-30T23:00:00Z  2020-10-01T01:00:00+0200

       AT_load_actual_entsoe_transparency  \
0                                     NaN
1                                  5946.0
2                                  5726.0
3                                  5347.0
4                                  5249.0
...                                   ...
50396                              6661.0
50397                              6336.0
50398                              5932.0
50399                              5628.0
50400                              5395.0

       AT_load_forecast_entsoe_transparency  AT_price_day_ahead  \
0                                       NaN                 NaN
1                                    6701.0                35.0
2                                    6593.0                45.0
3                                    6482.0                41.0
4                                    6454.0                38.0
...                                     ...                 ...
50396                                6656.0                 NaN
50397                                6310.0                 NaN
50398                                5813.0                 NaN
50399                                5424.0                 NaN
50400                                5204.0                 NaN

       AT_solar_generation_actual  AT_wind_onshore_generation_actual
0                             NaN                                NaN
1                             NaN                               69.0
2                             NaN                               64.0
3                             NaN                               65.0
4                             NaN                               64.0
...                           ...                                ...
50396                         NaN                             1847.0
50397                         NaN                             1723.0
50398                         NaN                             1771.0
50399                         NaN                             1779.0
50400                         NaN                             1661.0

[50401 rows x 7 columns]
              utc_timestamp        cet_cest_timestamp  \
0      2014-12-31T23:00:00Z  2015-01-01T00:00:00+0100
1      2015-01-01T00:00:00Z  2015-01-01T01:00:00+0100
2      2015-01-01T01:00:00Z  2015-01-01T02:00:00+0100
3      2015-01-01T02:00:00Z  2015-01-01T03:00:00+0100
4      2015-01-01T03:00:00Z  2015-01-01T04:00:00+0100
...                     ...                       ...
50396  2020-09-30T19:00:00Z  2020-09-30T21:00:00+0200
50397  2020-09-30T20:00:00Z  2020-09-30T22:00:00+0200
50398  2020-09-30T21:00:00Z  2020-09-30T23:00:00+0200
50399  2020-09-30T22:00:00Z  2020-10-01T00:00:00+0200
50400  2020-09-30T23:00:00Z  2020-10-01T01:00:00+0200

       BE_load_actual_entsoe_transparency  \
0                                     NaN
1                                  9484.0
2                                  9152.0
3                                  8799.0
4                                  8567.0
...                                   ...
50396                              9402.0
50397                              9219.0
50398                              8763.0
50399                              8131.0
50400                              7837.0

       BE_load_forecast_entsoe_transparency  BE_solar_generation_actual  \
0                                       NaN                         NaN
1                                    9897.0                         NaN
2                                    9521.0                         NaN
3                                    9135.0                         NaN
4                                    8909.0                         NaN
...                                     ...                         ...
50396                                9720.0                         NaN
50397                                9418.0                         NaN
50398                                8873.0                         NaN
50399                                8285.0                         NaN
50400                                7943.0                         NaN

       BE_wind_generation_actual  BE_wind_offshore_generation_actual  \
0                            NaN                                 NaN
1                            NaN                                 NaN
2                         734.81                              518.66
3                         766.64                              529.46
4                         733.13                              406.94
...                          ...                                 ...
50396                    1889.72                             1497.40
50397                    2154.67                             1688.06
50398                    2187.48                             1715.76
50399                    2225.62                             1739.17
50400                        NaN                                 NaN

       BE_wind_onshore_generation_actual
0                                    NaN
1                                    NaN
2                                 216.15
3                                 237.18
4                                 326.19
...                                  ...
50396                             392.32
50397                             466.61
50398                             471.72
50399                             486.45
50400                                NaN

[50401 rows x 8 columns]
              utc_timestamp        cet_cest_timestamp  \
0      2014-12-31T23:00:00Z  2015-01-01T00:00:00+0100
1      2015-01-01T00:00:00Z  2015-01-01T01:00:00+0100
2      2015-01-01T01:00:00Z  2015-01-01T02:00:00+0100
3      2015-01-01T02:00:00Z  2015-01-01T03:00:00+0100
4      2015-01-01T03:00:00Z  2015-01-01T04:00:00+0100
...                     ...                       ...
50396  2020-09-30T19:00:00Z  2020-09-30T21:00:00+0200
50397  2020-09-30T20:00:00Z  2020-09-30T22:00:00+0200
50398  2020-09-30T21:00:00Z  2020-09-30T23:00:00+0200
50399  2020-09-30T22:00:00Z  2020-10-01T00:00:00+0200
50400  2020-09-30T23:00:00Z  2020-10-01T01:00:00+0200

       BG_load_actual_entsoe_transparency  \
0                                     NaN
1                                     NaN
2                                  4585.0
3                                  4440.0
4                                  4418.0
...                                   ...
50396                              3871.0
50397                              3608.0
50398                              3263.0
50399                              3071.0
50400                                 NaN

       BG_load_forecast_entsoe_transparency  BG_solar_generation_actual  \
0                                       NaN                         NaN
1                                       NaN                         NaN
2                                       NaN                         NaN
3                                       NaN                         NaN
4                                       NaN                         NaN
...                                     ...                         ...
50396                                3798.0                         NaN
50397                                3506.0                         NaN
50398                                3243.0                         NaN
50399                                3079.0                         NaN
50400                                   NaN                         NaN

       BG_wind_onshore_generation_actual
0                                    NaN
1                                    NaN
2                                  479.0
3                                  465.0
4                                  460.0
...                                  ...
50396                              215.0
50397                              316.0
50398                              314.0
50399                              225.0
50400                                NaN

[50401 rows x 6 columns]
              utc_timestamp        cet_cest_timestamp  \
0      2014-12-31T23:00:00Z  2015-01-01T00:00:00+0100
1      2015-01-01T00:00:00Z  2015-01-01T01:00:00+0100
2      2015-01-01T01:00:00Z  2015-01-01T02:00:00+0100
3      2015-01-01T02:00:00Z  2015-01-01T03:00:00+0100
4      2015-01-01T03:00:00Z  2015-01-01T04:00:00+0100
...                     ...                       ...
50396  2020-09-30T19:00:00Z  2020-09-30T21:00:00+0200
50397  2020-09-30T20:00:00Z  2020-09-30T22:00:00+0200
50398  2020-09-30T21:00:00Z  2020-09-30T23:00:00+0200
50399  2020-09-30T22:00:00Z  2020-10-01T00:00:00+0200
50400  2020-09-30T23:00:00Z  2020-10-01T01:00:00+0200

       CH_load_actual_entsoe_transparency  \
0                                     NaN
1                                     NaN
2                                 7640.14
3                                 7391.44
4                                 7332.57
...                                   ...
50396                             6334.81
50397                             6510.08
50398                             6812.27
50399                             6381.76
50400                                 NaN

       CH_load_forecast_entsoe_transparency  CH_solar_capacity  \
0                                       NaN                NaN
1                                       NaN              455.0
2                                   7696.04              455.0
3                                   7447.53              455.0
4                                   7381.67              455.0
...                                     ...                ...
50396                               6385.00                NaN
50397                               6643.71                NaN
50398                               6793.47                NaN
50399                               6381.76                NaN
50400                                   NaN                NaN

       CH_solar_generation_actual  CH_wind_onshore_capacity  \
0                             NaN                       NaN
1                             NaN                      44.0
2                            0.05                      44.0
3                            0.07                      44.0
4                            0.07                      44.0
...                           ...                       ...
50396                         NaN                       NaN
50397                         NaN                       NaN
50398                         NaN                       NaN
50399                         NaN                       NaN
50400                         NaN                       NaN

       CH_wind_onshore_generation_actual
0                                    NaN
1                                    NaN
2                                  14.00
3                                  12.80
4                                  13.73
...                                  ...
50396                                NaN
50397                                NaN
50398                                NaN
50399                                NaN
50400                                NaN

[50401 rows x 8 columns]
              utc_timestamp        cet_cest_timestamp  \
0      2014-12-31T23:00:00Z  2015-01-01T00:00:00+0100
1      2015-01-01T00:00:00Z  2015-01-01T01:00:00+0100
2      2015-01-01T01:00:00Z  2015-01-01T02:00:00+0100
3      2015-01-01T02:00:00Z  2015-01-01T03:00:00+0100
4      2015-01-01T03:00:00Z  2015-01-01T04:00:00+0100
...                     ...                       ...
50396  2020-09-30T19:00:00Z  2020-09-30T21:00:00+0200
50397  2020-09-30T20:00:00Z  2020-09-30T22:00:00+0200
50398  2020-09-30T21:00:00Z  2020-09-30T23:00:00+0200
50399  2020-09-30T22:00:00Z  2020-10-01T00:00:00+0200
50400  2020-09-30T23:00:00Z  2020-10-01T01:00:00+0200

       CY_load_actual_entsoe_transparency  \
0                                     NaN
1                                     NaN
2                                     NaN
3                                     NaN
4                                     NaN
...                                   ...
50396                               500.0
50397                               463.0
50398                               430.0
50399                               401.0
50400                               387.0

       CY_load_forecast_entsoe_transparency  CY_wind_onshore_generation_actual
0                                       NaN                                NaN
1                                       NaN                                NaN
2                                       NaN                                NaN
3                                       NaN                                NaN
4                                       NaN                                NaN
...                                     ...                                ...
50396                                   NaN                               27.0
50397                                   NaN                               28.0
50398                                   NaN                               25.0
50399                                   NaN                               18.0
50400                                   NaN                               23.0

[50401 rows x 5 columns]
              utc_timestamp        cet_cest_timestamp  \
0      2014-12-31T23:00:00Z  2015-01-01T00:00:00+0100
1      2015-01-01T00:00:00Z  2015-01-01T01:00:00+0100
2      2015-01-01T01:00:00Z  2015-01-01T02:00:00+0100
3      2015-01-01T02:00:00Z  2015-01-01T03:00:00+0100
4      2015-01-01T03:00:00Z  2015-01-01T04:00:00+0100
...                     ...                       ...
50396  2020-09-30T19:00:00Z  2020-09-30T21:00:00+0200
50397  2020-09-30T20:00:00Z  2020-09-30T22:00:00+0200
50398  2020-09-30T21:00:00Z  2020-09-30T23:00:00+0200
50399  2020-09-30T22:00:00Z  2020-10-01T00:00:00+0200
50400  2020-09-30T23:00:00Z  2020-10-01T01:00:00+0200

       CZ_load_actual_entsoe_transparency  \
0                                     NaN
1                                     NaN
2                                 5957.57
3                                 5878.87
4                                 5827.80
...                                   ...
50396                             7605.02
50397                             7173.36
50398                             6763.14
50399                             6416.42
50400                                 NaN

       CZ_load_forecast_entsoe_transparency  CZ_solar_generation_actual  \
0                                       NaN                         NaN
1                                       NaN                         NaN
2                                    5987.0                         NaN
3                                    5845.0                         NaN
4                                    5786.0                         NaN
...                                     ...                         ...
50396                                7418.0                         NaN
50397                                6979.0                         NaN
50398                                6521.0                         NaN
50399                                6335.0                         NaN
50400                                   NaN                         NaN

       CZ_wind_onshore_generation_actual
0                                    NaN
1                                    NaN
2                                  38.48
3                                  56.20
4                                  71.21
...                                  ...
50396                              58.73
50397                              60.90
50398                              57.06
50399                              50.17
50400                                NaN

[50401 rows x 6 columns]
              utc_timestamp        cet_cest_timestamp  \
0      2014-12-31T23:00:00Z  2015-01-01T00:00:00+0100
1      2015-01-01T00:00:00Z  2015-01-01T01:00:00+0100
2      2015-01-01T01:00:00Z  2015-01-01T02:00:00+0100
3      2015-01-01T02:00:00Z  2015-01-01T03:00:00+0100
4      2015-01-01T03:00:00Z  2015-01-01T04:00:00+0100
...                     ...                       ...
50396  2020-09-30T19:00:00Z  2020-09-30T21:00:00+0200
50397  2020-09-30T20:00:00Z  2020-09-30T22:00:00+0200
50398  2020-09-30T21:00:00Z  2020-09-30T23:00:00+0200
50399  2020-09-30T22:00:00Z  2020-10-01T00:00:00+0200
50400  2020-09-30T23:00:00Z  2020-10-01T01:00:00+0200

       DK_load_actual_entsoe_transparency  \
0                                     NaN
1                                     NaN
2                                 3100.02
3                                 2980.39
4                                 2933.49
...                                   ...
50396                             4057.22
50397                             3523.75
50398                             3114.95
50399                             2926.36
50400                                 NaN

       DK_load_forecast_entsoe_transparency  DK_solar_capacity  \
0                                       NaN                NaN
1                                       NaN              489.0
2                                    3126.8              489.0
3                                    3019.0              489.0
4                                    2976.3              489.0
...                                     ...                ...
50396                                3998.0                NaN
50397                                3668.0                NaN
50398                                3359.0                NaN
50399                                2922.0                NaN
50400                                   NaN                NaN

       DK_solar_generation_actual  DK_wind_capacity  \
0                             NaN               NaN
1                             NaN            4643.0
2                             NaN            4643.0
3                             NaN            4643.0
4                             NaN            4643.0
...                           ...               ...
50396                         NaN               NaN
50397                         NaN               NaN
50398                         NaN               NaN
50399                         NaN               NaN
50400                         NaN               NaN

       DK_wind_generation_actual  DK_wind_offshore_capacity  \
0                            NaN                        NaN
1                            NaN                     1264.0
2                        2357.33                     1264.0
3                        2387.35                     1264.0
4                        2594.47                     1264.0
...                          ...                        ...
50396                    1492.40                        NaN
50397                    1690.23                        NaN
50398                    1800.90                        NaN
50399                    2014.26                        NaN
50400                        NaN                        NaN

       DK_wind_offshore_generation_actual  ...  DK_1_wind_generation_actual  \
0                                     NaN  ...                          NaN

In [63]:
save_dataset_path = "dataset/"

for code, data in df_each_area.items():
    filename = save_dataset_path + code + '.csv'
    data.to_csv(filename, index=False)

In [64]:
df_AT__

,utc_timestamp,cet_cest_timestamp,AT_load_actual_entsoe_transparency,AT_load_forecast_entsoe_transparency,AT_price_day_ahead,AT_solar_generation_actual,AT_wind_onshore_generation_actual
0,2014-12-31T23:00:00Z,2015-01-01T00:00:00+0100,NaN,NaN,NaN,NaN,NaN
1,2015-01-01T00:00:00Z,2015-01-01T01:00:00+0100,5946.0,6701.0,35.0,NaN,69.0
2,2015-01-01T01:00:00Z,2015-01-01T02:00:00+0100,5726.0,6593.0,45.0,NaN,64.0
3,2015-01-01T02:00:00Z,2015-01-01T03:00:00+0100,5347.0,6482.0,41.0,NaN,65.0
4,2015-01-01T03:00:00Z,2015-01-01T04:00:00+0100,5249.0,6454.0,38.0,NaN,64.0
...,...,...,...,...,...,...,...
50396,2020-09-30T19:00:00Z,2020-09-30T21:00:00+0200,6661.0,6656.0,NaN,NaN,1847.0
50397,2020-09-30T20:00:00Z,2020-09-30T22:00:00+0200,6336.0,6310.0,NaN,NaN,1723.0
50398,2020-09-30T21:00:00Z,2020-09-30T23:00:00+0200,5932.0,5813.0,NaN,NaN,1771.0
50399,2020-09-30T22:00:00Z,2020-10-01T00:00:00+0200,5628.0,5424.0,NaN,NaN,1779.0
50400,2020-09-30T23:00:00Z,2020-10-01T01:00:00+0200,5395.0,5204.0,NaN,NaN,1661.0

In [65]:
df_AT__.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50401 entries, 0 to 50400
Data columns (total 7 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   utc_timestamp                         50401 non-null  object
 1   cet_cest_timestamp                    50401 non-null  object
 2   AT_load_actual_entsoe_transparency    50400 non-null  float64
 3   AT_load_forecast_entsoe_transparency  50400 non-null  float64
 4   AT_price_day_ahead                    32845 non-null  float64
 5   AT_solar_generation_actual            50339 non-null  float64
 6   AT_wind_onshore_generation_actual     50352 non-null  float64
dtypes: float64(5), object(2)
memory usage: 2.7+ MB